
[window]
width = 1440
height = 900
title = "Test Game"
icon_path = ""
fps_cap = 60
render_scale = 1
resizable = false
fullscreen = false
debug = true

[shaders]
opengl = true
fragment_path = "./tests/frag.frag"

[input]
quit = "escape"
up = "W"
left = "A"
down = "S"
right = "D"
jump = "space"
action_1 = "R"
action_2 = "F"
util_1 = "Q"
util_2 = "E"

[asset]
asset_path = "./tests/assets/"

[ecs]
enable = true
component_path = ""
domain_id = "default"
